# Configuration for BrainGNNVanilla Regression
downstream_dataset: 'abide'  # 'abide' or 'adhd'
upstream_model: 'mass' # jepa, mass or lm
n_roi: 100

uid: 'braingnnvanilla_${upstream_model}_${downstream_dataset}_reg_exp'

# Random seed for reproducibility
seed: 42

# Data configuration
data:
  dataset_class: 'FMRIGraphDataset'
  data_dir: 'data/${downstream_dataset}_graph/${upstream_model}'
  train_paths_txt: '${data.data_dir}/00_${upstream_model}_train_npy_paths.txt'
  train_labels_csv: '${data.data_dir}/00_${upstream_model}_train_matched_labels.csv'
  val_paths_txt: '${data.data_dir}/00_${upstream_model}_val_npy_paths.txt'
  val_labels_csv: '${data.data_dir}/00_${upstream_model}_val_matched_labels.csv'
  test_paths_txt: '${data.data_dir}/00_${upstream_model}_test_npy_paths.txt'
  test_labels_csv: '${data.data_dir}/00_${upstream_model}_test_matched_labels.csv'
  path_col: 'npy_file'
  label_col: 'AGE_NORM' # uniform, label column is 'AGE_NORM'
  use_adj_as_x: true

# Model configuration
model:
  name: 'BrainGNNVanilla'
  params:
    indim: ${n_roi}
    ratio: 0.5
    nclass: 1  # For regression output
    R: ${n_roi}  # Added model parameter 'R'


# Task configuration
task:
  name: 'graph_regression'
  params:
    batch_size: 64  # better than 128
    num_epochs: 100
    learning_rate: 0.01
    weight_decay: 0.005
    num_workers: 8

# Logging
log_every: 10
experiment_name: '${uid}-lr_${task.params.learning_rate}-wd_${task.params.weight_decay}-bs_${task.params.batch_size}-ep_${task.params.num_epochs}-sd_${seed}'
log_dir: './checkpoints/checkpoints/${experiment_name}/logs'
checkpoint_dir: './checkpoints/checkpoints/${experiment_name}'
